// Drizzle schema barrel. drizzle-kit reads THIS file (see drizzle.config.ts).
//
// `auth-schema.ts` is auto-generated by `npx @better-auth/cli generate`.
// Re-run the CLI any time you add/change Better Auth plugins or options, then
// re-export the new tables here if needed (the export below is sufficient for
// the default user/session/account/verification set).

export * from "./auth-schema";
export * from "./idea-schema";

// Add your own application tables below and export them here.
// export * from "./ideas";
// export * from "./votes";
